version: '3.8'
services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: agromano
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d

  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      DB_USER: postgres
      DB_HOST: db
      DB_NAME: agromano
      DB_PASSWORD: 12345
      DB_PORT: 5432
      # Otras variables de entorno necesarias
    ports:
      - "5000:5000"
    command: node index.js

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"
    command: npm run dev -- --host
    

volumes:
  pgdata: